### PR TITLE
Instructions for app-nav component.

### PR DESCRIPTION
**Pull request by blackbaud-johnly**
@Blackbaud-LindseyRix pointed out that we need more instructions on the omnibar than just a link to the omnibar docs site, but I'd like to go ahead and get this update in first. This at least improves what we currently have, and we can flesh out the omnibar documentation after this is in.

### CODE REVIEW

**Comment by Blackbaud-LindseyRix** [comment]
All the content is written great and of course, technically accurate. Do you think it's going to be too difficult for non-technical users to understand how to edit the navigation?

**Comment by blackbaud-johnly** [comment]
@Blackbaud-LindseyRix, I can rewrite this to edit out the portion about localization stings and replace that part with a note linking to the SKY UX tutorials if users want to use localization strings if you think that would be easier to follow. What do you think?

**Comment by Blackbaud-LindseyRix** [comment]
I think pushing localization strings to skyux would be great. For those who know and want it, they should be fine going to SKY UX. For those who just want to update their nav for docs sites, they can to that info faster.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-LindseyRix, I updated to de-emphasize the localization strings as suggested. Can you take another look and see if this seems good to go now?

**Pull request merged**
