### PR TITLE
Added link to new code-block docs

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://host.nxt.blackbaud.com/stache?_sp.spa=pr-add-code-block-link](https://host.nxt.blackbaud.com/stache?_sp.spa=pr-add-code-block-link)

**Comment by Blackbaud-LindseyRix** [comment]
Are you going to add the new property?

**Comment by Blackbaud-BobbyEarl** [comment]
Not here.  This component is deprecated.  There will be PR to the current docs page that I added a link for here.

**Comment by Blackbaud-LindseyRix** [comment]
Actually, we maintain a simplified version of the supported docs here. If you look closer at the docs page. This page is still maintained and we try to keep those doing Stache documentation on this site as much as possible. Much of the content on the SKY UX components page is way too complicated for a person who's just doing documentation. If you don't want to document the property here, I can.

**Comment by Blackbaud-BobbyEarl** [comment]
Can you help me understand what is complicated on [this page](https://developer.blackbaud.com/skyux/components/code-block) that is not too complicated on [this one](https://developer.blackbaud.com/stache/components/code-block)?

I would rather come to a resolution where we're not maintaining two sets of nearly identical documentation regarding this (and the other deprecated) components.

**Comment by Blackbaud-LindseyRix** [comment]
Don't worry about it, I'm happy to do it myself. You updating the link is good enough for now.

**Pull request merged**
